import express from "express";
import dotenv from "dotenv";
import { Room, RoomEvent, AudioSource } from "@livekit/rtc-node";

dotenv.config();

const app = express();
app.use(express.json());

const PORT = process.env.PORT || 3000;

// We keep LIVEKIT_WS_URL as a fallback if caller doesn't send one,
// but we do NOT generate tokens here anymore.
const LIVEKIT_WS_URL = process.env.LIVEKIT_WS_URL || "";
const ELEVENLABS_API_KEY = process.env.ELEVENLABS_API_KEY || "";

console.log("21AI Agent Worker booted");
console.log("LIVEKIT_WS_URL:", LIVEKIT_WS_URL ? "✓" : "⚠️ missing (will expect from body)");
console.log("ELEVENLABS_API_KEY:", ELEVENLABS_API_KEY ? "✓" : "⚠️ missing");

/**
 * Simple ElevenLabs TTS → PCM16 buffer
 */
async function ttsElevenLabs(text) {
  try {
    if (!ELEVENLABS_API_KEY) {
      console.warn("⚠️ ELEVENLABS_API_KEY not set, skipping TTS");
      return null;
    }

    const voiceId = "EXAVITQu4vr4xnSDxMaL"; // default demo voice

    const res = await fetch(
      `https://api.elevenlabs.io/v1/text-to-speech/${voiceId}`,
      {
        method: "POST",
        headers: {
          "xi-api-key": ELEVENLABS_API_KEY,
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          text,
          model_id: "eleven_multilingual_v2",
          voice_settings: {
            stability: 0.4,
            similarity_boost: 0.8,
          },
          output_format: "pcm_16000",
        }),
      }
    );

    if (!res.ok) {
      console.error("❌ ElevenLabs TTS Error:", await res.text());
      return null;
    }

    const buf = Buffer.from(await res.arrayBuffer());
    console.log("🎧 ElevenLabs PCM bytes:", buf.length);
    return buf;
  } catch (err) {
    console.error("❌ ElevenLabs request failed:", err);
    return null;
  }
}

/**
 * Connect agent to LiveKit using the token generated by Supabase
 */
async function startAgent({ livekitUrl, roomName, agentId, agentToken }) {
  try {
    const urlToUse = livekitUrl || LIVEKIT_WS_URL;
    if (!urlToUse) {
      throw new Error("No LiveKit URL provided to worker");
    }
    if (!agentToken) {
      throw new Error("No agentToken provided to worker");
    }

    console.log("🤖 startAgent() connecting to:", urlToUse);
    console.log("   roomName:", roomName);
    console.log("   agentId:", agentId);

    const room = new Room();

    // basic logging
    room.on(RoomEvent.ParticipantConnected, (p) => {
      console.log("👤 Participant connected:", p.identity);
    });
    room.on(RoomEvent.TrackSubscribed, (track, pub, p) => {
      console.log("🎧 Subscribed to track:", track.kind, "from", p.identity);
    });
    room.on(RoomEvent.Error, (err) => {
      console.error("❌ Room error:", err);
    });

    // connect with the JWT generated in Supabase
    await room.connect(urlToUse, agentToken);
    console.log("✅ Agent joined room:", roomName);
    console.log("   Local identity:", room.localParticipant.identity);

    // publish a silent track so the room sees this participant
    const audioSource = new AudioSource(16000, 1);
    const track = audioSource.createTrack();
    await room.localParticipant.publishTrack(track);
    console.log("🔊 Agent audio track published");

    // one-time greeting
    const greeting =
      "Hello, this is your twenty one A I receptionist. How can I help you today?";
    const pcm = await ttsElevenLabs(greeting);

    if (pcm) {
      console.log("📤 Writing greeting audio to LiveKit");
      audioSource.write(pcm);
    } else {
      console.log("⚠️ No PCM from ElevenLabs, nothing to play");
    }

    // keep connection open; Railway will keep process alive
  } catch (err) {
    console.error("❌ startAgent failed:", err);
  }
}

// ---------------------------------------------------------------------
// Routes
// ---------------------------------------------------------------------

// Healthcheck
app.get("/", (req, res) => {
  res.send("21AI Agent Worker is running ✅");
});

// Called from Supabase edge function
app.post("/start-session", async (req, res) => {
  try {
    const { livekitUrl, roomName, agentId, agentToken } = req.body || {};

    console.log("⚡ /start-session body:", JSON.stringify(req.body));

    if (!roomName || !agentToken) {
      return res.status(400).json({
        ok: false,
        error: "roomName and agentToken are required",
      });
    }

    // fire & forget
    startAgent({ livekitUrl, roomName, agentId, agentToken });

    return res.json({ ok: true });
  } catch (err) {
    console.error("❌ /start-session handler crashed:", err);
    return res.status(500).json({ ok: false, error: "worker_crash" });
  }
});

// Start server
app.listen(PORT, () => {
  console.log(`🚀 Worker ready on port ${PORT}`);
});
