// index.js - 21ai-agent-worker
// Server-side agent that joins a LiveKit room and plays an ElevenLabs greeting

import express from "express";
import dotenv from "dotenv";
import {
  Room,
  RoomEvent,
  AudioSource,
  LocalAudioTrack,
  TrackPublishOptions,
  TrackSource,
  AudioFrame,
} from "@livekit/rtc-node";

dotenv.config();

const app = express();
app.use(express.json());

const PORT = process.env.PORT || 3000;

// ENV VARS FROM RAILWAY
const LIVEKIT_WS_URL = process.env.LIVEKIT_WS_URL;
const ELEVENLABS_API_KEY = process.env.ELEVENLABS_API_KEY;

console.log("21AI Agent Worker booted");
console.log("LIVEKIT_WS_URL:", LIVEKIT_WS_URL ? "✓" : "❌ missing");
console.log("ELEVENLABS_API_KEY:", ELEVENLABS_API_KEY ? "✓" : "❌ missing");

if (!LIVEKIT_WS_URL || !ELEVENLABS_API_KEY) {
  console.warn("⚠️ Missing LiveKit or ElevenLabs env vars");
}

// ---------------------------------------------------------------------
// ElevenLabs TTS → Int16Array PCM @ 16kHz mono
// ---------------------------------------------------------------------
async function ttsElevenLabs(text) {
  try {
    const voiceId = "EXAVITQu4vr4xnSDxMaL"; // default voice

    const res = await fetch(
      `https://api.elevenlabs.io/v1/text-to-speech/${voiceId}`,
      {
        method: "POST",
        headers: {
          "xi-api-key": ELEVENLABS_API_KEY,
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          text,
          model_id: "eleven_multilingual_v2",
          voice_settings: {
            stability: 0.4,
            similarity_boost: 0.8,
          },
          // 16-bit PCM, 16kHz, mono – perfect for rtc-node
          output_format: "pcm_16000",
        }),
      }
    );

    if (!res.ok) {
      console.error("❌ ElevenLabs TTS Error:", await res.text());
      return null;
    }

    const arrayBuffer = await res.arrayBuffer();
    const buffer = Buffer.from(arrayBuffer);

    // Convert raw PCM bytes → Int16Array
    const int16 = new Int16Array(
      buffer.buffer,
      buffer.byteOffset,
      buffer.byteLength / 2
    );

    console.log("🎧 ElevenLabs PCM samples:", int16.length);
    return int16;
  } catch (err) {
    console.error("❌ ElevenLabs request failed:", err);
    return null;
  }
}

// ---------------------------------------------------------------------
// Agent joins room & plays greeting
// ---------------------------------------------------------------------
async function startAgent({ livekitUrl, roomName, agentId, agentToken }) {
  const identity = `agent_${agentId}`;
  console.log("🤖 startAgent -> room:", roomName);
  console.log("🤖 startAgent -> identity:", identity);
  console.log("🤖 startAgent -> url:", livekitUrl);

  const sampleRate = 16000;
  const channels = 1;

  try {
    // 1) Connect to LiveKit room using the token generated by Supabase
    const room = new Room();

    room.on(RoomEvent.ParticipantConnected, (p) => {
      console.log("👤 Participant connected:", p.identity);
    });

    room.on(RoomEvent.TrackSubscribed, (track, pub, participant) => {
      console.log(
        "🎧 Agent subscribed to track:",
        track.kind,
        "from",
        participant.identity
      );
    });

    room.on(RoomEvent.Disconnected, () => {
      console.log("👋 Agent disconnected from room:", roomName);
    });

    await room.connect(livekitUrl, agentToken, {
      autoSubscribe: true,
      dynacast: true,
    });

    console.log("✅ Agent connected to LiveKit room:", roomName);

    // 2) Create AudioSource + LocalAudioTrack (correct rtc-node API)
    const source = new AudioSource(sampleRate, channels);
    const track = LocalAudioTrack.createAudioTrack("agent-voice", source);
    const options = new TrackPublishOptions();
    options.source = TrackSource.SOURCE_MICROPHONE;

    await room.localParticipant.publishTrack(track, options);
    console.log("🔊 Agent audio track published");

    // 3) Generate greeting via ElevenLabs
    const greeting =
      "Hello, this is your twenty one A I receptionist. How can I help you today?";
    const samples = await ttsElevenLabs(greeting);

    if (!samples) {
      console.warn("⚠️ No PCM samples from ElevenLabs, skipping playback");
      return;
    }

    // 4) Stream samples into LiveKit as AudioFrames (20ms chunks)
    const frameDurationMs = 20;
    const samplesPerFrame = (sampleRate * frameDurationMs) / 1000; // 320

    console.log("📤 Streaming ElevenLabs audio into room...");

    let offset = 0;
    while (offset < samples.length) {
      const remaining = samples.length - offset;
      const frameSize = Math.min(samplesPerFrame, remaining);

      const frame = new AudioFrame(
        samples.slice(offset, offset + frameSize),
        sampleRate,
        channels,
        frameSize / channels
      );

      await source.captureFrame(frame);
      offset += frameSize;

      // crude pacing so we roughly match realtime playback
      await new Promise((r) => setTimeout(r, frameDurationMs));
    }

    console.log("✅ Finished streaming greeting audio");

    // keep the room alive a bit so audio finishes playing on the client
    setTimeout(async () => {
      console.log("🔚 Disconnecting agent from room:", roomName);
      await room.disconnect();
    }, 5000);
  } catch (err) {
    console.error("❌ startAgent failed:", err);
  }
}

// ---------------------------------------------------------------------
// API routes
// ---------------------------------------------------------------------

// Healthcheck
app.get("/", (req, res) => {
  res.send("21AI Agent Worker is running ✅");
});

// Supabase → worker
app.post("/start-session", async (req, res) => {
  try {
    console.log("⚡ /start-session body:", JSON.stringify(req.body));
    const { livekitUrl, roomName, agentId, agentToken } = req.body || {};

    if (!livekitUrl || !roomName || !agentId || !agentToken) {
      console.error("❌ Missing fields in /start-session body");
      return res.status(400).json({
        ok: false,
        error: "missing_fields",
      });
    }

    // Fire-and-forget: don’t block the HTTP response
    startAgent({ livekitUrl, roomName, agentId, agentToken });

    return res.json({
      ok: true,
      roomName,
      agentId,
    });
  } catch (err) {
    console.error("❌ /start-session failed:", err);
    return res.status(500).json({
      ok: false,
      error: "worker_crash",
    });
  }
});

// Start server
app.listen(PORT, () => {
  console.log(`🚀 Worker ready on port ${PORT}`);
});
